// Auto-generated by scripts/generate_responsive_images.py
// Provides static responsive srcSet values for Azure Static Website export.

export const responsiveImages: Record<string, { width: number; src: string }[]> = {
  "/images/307033505_515019567300167_4558219091365422579_n.jpeg": [
    {
      "width": 96,
      "src": "/images/responsive/307033505_515019567300167_4558219091365422579_n-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/307033505_515019567300167_4558219091365422579_n-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/307033505_515019567300167_4558219091365422579_n-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/307033505_515019567300167_4558219091365422579_n-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/307033505_515019567300167_4558219091365422579_n-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/307033505_515019567300167_4558219091365422579_n-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/307033505_515019567300167_4558219091365422579_n-1024.webp"
    },
    {
      "width": 1280,
      "src": "/images/responsive/307033505_515019567300167_4558219091365422579_n-1280.webp"
    },
    {
      "width": 2048,
      "src": "/images/responsive/307033505_515019567300167_4558219091365422579_n-2048.webp"
    }
  ],
  "/images/AboutUsPic-1024x682.png": [
    {
      "width": 96,
      "src": "/images/responsive/AboutUsPic-1024x682-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/AboutUsPic-1024x682-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/AboutUsPic-1024x682-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/AboutUsPic-1024x682-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/AboutUsPic-1024x682-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/AboutUsPic-1024x682-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/AboutUsPic-1024x682-1024.webp"
    }
  ],
  "/images/CARDFIGHT-VG-JAPAN.png": [
    {
      "width": 96,
      "src": "/images/responsive/CARDFIGHT-VG-JAPAN-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/CARDFIGHT-VG-JAPAN-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/CARDFIGHT-VG-JAPAN-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/CARDFIGHT-VG-JAPAN-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/CARDFIGHT-VG-JAPAN-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/CARDFIGHT-VG-JAPAN-768.webp"
    },
    {
      "width": 842,
      "src": "/images/responsive/CARDFIGHT-VG-JAPAN-842.webp"
    }
  ],
  "/images/ConfirmationV2.png": [
    {
      "width": 96,
      "src": "/images/responsive/ConfirmationV2-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/ConfirmationV2-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/ConfirmationV2-320.webp"
    },
    {
      "width": 372,
      "src": "/images/responsive/ConfirmationV2-372.webp"
    }
  ],
  "/images/DTB02_mediakit_banner-1.jpg": [
    {
      "width": 96,
      "src": "/images/responsive/DTB02_mediakit_banner-1-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/DTB02_mediakit_banner-1-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/DTB02_mediakit_banner-1-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/DTB02_mediakit_banner-1-480.webp"
    },
    {
      "width": 500,
      "src": "/images/responsive/DTB02_mediakit_banner-1-500.webp"
    }
  ],
  "/images/EmailIcon.png": [],
  "/images/FB-price-banner2.jpg": [
    {
      "width": 96,
      "src": "/images/responsive/FB-price-banner2-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/FB-price-banner2-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/FB-price-banner2-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/FB-price-banner2-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/FB-price-banner2-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/FB-price-banner2-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/FB-price-banner2-1024.webp"
    }
  ],
  "/images/FormV2.png": [
    {
      "width": 96,
      "src": "/images/responsive/FormV2-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/FormV2-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/FormV2-320.webp"
    },
    {
      "width": 372,
      "src": "/images/responsive/FormV2-372.webp"
    }
  ],
  "/images/LocationIcon.png": [],
  "/images/MarketingV2.png": [
    {
      "width": 96,
      "src": "/images/responsive/MarketingV2-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/MarketingV2-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/MarketingV2-320.webp"
    },
    {
      "width": 372,
      "src": "/images/responsive/MarketingV2-372.webp"
    }
  ],
  "/images/Media-Kit-Template-BT01.jpg": [
    {
      "width": 96,
      "src": "/images/responsive/Media-Kit-Template-BT01-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/Media-Kit-Template-BT01-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/Media-Kit-Template-BT01-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/Media-Kit-Template-BT01-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/Media-Kit-Template-BT01-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/Media-Kit-Template-BT01-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/Media-Kit-Template-BT01-1024.webp"
    }
  ],
  "/images/Media-Kit-Template_-BT01_MY_v2_1980_JPG.jpg": [
    {
      "width": 96,
      "src": "/images/responsive/Media-Kit-Template_-BT01_MY_v2_1980_JPG-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/Media-Kit-Template_-BT01_MY_v2_1980_JPG-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/Media-Kit-Template_-BT01_MY_v2_1980_JPG-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/Media-Kit-Template_-BT01_MY_v2_1980_JPG-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/Media-Kit-Template_-BT01_MY_v2_1980_JPG-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/Media-Kit-Template_-BT01_MY_v2_1980_JPG-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/Media-Kit-Template_-BT01_MY_v2_1980_JPG-1024.webp"
    },
    {
      "width": 1280,
      "src": "/images/responsive/Media-Kit-Template_-BT01_MY_v2_1980_JPG-1280.webp"
    },
    {
      "width": 1920,
      "src": "/images/responsive/Media-Kit-Template_-BT01_MY_v2_1980_JPG-1920.webp"
    }
  ],
  "/images/PhoneIcon.png": [],
  "/images/Poster_VMC22_2-01-1.png": [
    {
      "width": 96,
      "src": "/images/responsive/Poster_VMC22_2-01-1-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/Poster_VMC22_2-01-1-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/Poster_VMC22_2-01-1-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/Poster_VMC22_2-01-1-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/Poster_VMC22_2-01-1-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/Poster_VMC22_2-01-1-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/Poster_VMC22_2-01-1-1024.webp"
    },
    {
      "width": 1080,
      "src": "/images/responsive/Poster_VMC22_2-01-1-1080.webp"
    }
  ],
  "/images/Poster_VMC22_Johor-Bahru_V7.png": [
    {
      "width": 96,
      "src": "/images/responsive/Poster_VMC22_Johor-Bahru_V7-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/Poster_VMC22_Johor-Bahru_V7-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/Poster_VMC22_Johor-Bahru_V7-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/Poster_VMC22_Johor-Bahru_V7-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/Poster_VMC22_Johor-Bahru_V7-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/Poster_VMC22_Johor-Bahru_V7-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/Poster_VMC22_Johor-Bahru_V7-1024.webp"
    },
    {
      "width": 1080,
      "src": "/images/responsive/Poster_VMC22_Johor-Bahru_V7-1080.webp"
    }
  ],
  "/images/PreOrderV2.png": [
    {
      "width": 96,
      "src": "/images/responsive/PreOrderV2-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/PreOrderV2-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/PreOrderV2-320.webp"
    },
    {
      "width": 372,
      "src": "/images/responsive/PreOrderV2-372.webp"
    }
  ],
  "/images/RetailerV2.png": [
    {
      "width": 96,
      "src": "/images/responsive/RetailerV2-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/RetailerV2-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/RetailerV2-320.webp"
    },
    {
      "width": 372,
      "src": "/images/responsive/RetailerV2-372.webp"
    }
  ],
  "/images/SD01-05_Kini_Di_Pasaran.jpeg": [
    {
      "width": 96,
      "src": "/images/responsive/SD01-05_Kini_Di_Pasaran-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/SD01-05_Kini_Di_Pasaran-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/SD01-05_Kini_Di_Pasaran-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/SD01-05_Kini_Di_Pasaran-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/SD01-05_Kini_Di_Pasaran-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/SD01-05_Kini_Di_Pasaran-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/SD01-05_Kini_Di_Pasaran-1024.webp"
    },
    {
      "width": 1280,
      "src": "/images/responsive/SD01-05_Kini_Di_Pasaran-1280.webp"
    }
  ],
  "/images/SellV2.png": [
    {
      "width": 96,
      "src": "/images/responsive/SellV2-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/SellV2-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/SellV2-320.webp"
    },
    {
      "width": 372,
      "src": "/images/responsive/SellV2-372.webp"
    }
  ],
  "/images/SignUpV2.png": [
    {
      "width": 96,
      "src": "/images/responsive/SignUpV2-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/SignUpV2-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/SignUpV2-320.webp"
    },
    {
      "width": 372,
      "src": "/images/responsive/SignUpV2-372.webp"
    }
  ],
  "/images/VG-D-BT08-2-1024x576.webp": [
    {
      "width": 96,
      "src": "/images/responsive/VG-D-BT08-2-1024x576-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/VG-D-BT08-2-1024x576-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/VG-D-BT08-2-1024x576-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/VG-D-BT08-2-1024x576-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/VG-D-BT08-2-1024x576-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/VG-D-BT08-2-1024x576-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/VG-D-BT08-2-1024x576-1024.webp"
    }
  ],
  "/images/Vg_new_logo.png": [
    {
      "width": 96,
      "src": "/images/responsive/Vg_new_logo-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/Vg_new_logo-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/Vg_new_logo-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/Vg_new_logo-480.webp"
    },
    {
      "width": 600,
      "src": "/images/responsive/Vg_new_logo-600.webp"
    }
  ],
  "/images/WSBP-Uma.jpg": [
    {
      "width": 96,
      "src": "/images/responsive/WSBP-Uma-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/WSBP-Uma-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/WSBP-Uma-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/WSBP-Uma-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/WSBP-Uma-640.webp"
    },
    {
      "width": 707,
      "src": "/images/responsive/WSBP-Uma-707.webp"
    }
  ],
  "/images/bt11.jpg": [
    {
      "width": 96,
      "src": "/images/responsive/bt11-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/bt11-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/bt11-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/bt11-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/bt11-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/bt11-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/bt11-1024.webp"
    },
    {
      "width": 1280,
      "src": "/images/responsive/bt11-1280.webp"
    },
    {
      "width": 1920,
      "src": "/images/responsive/bt11-1920.webp"
    }
  ],
  "/images/cropped-Logo-EG.png": [
    {
      "width": 96,
      "src": "/images/responsive/cropped-Logo-EG-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/cropped-Logo-EG-160.webp"
    },
    {
      "width": 200,
      "src": "/images/responsive/cropped-Logo-EG-200.webp"
    }
  ],
  "/images/date_a_live_booster2.jpg": [
    {
      "width": 96,
      "src": "/images/responsive/date_a_live_booster2-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/date_a_live_booster2-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/date_a_live_booster2-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/date_a_live_booster2-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/date_a_live_booster2-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/date_a_live_booster2-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/date_a_live_booster2-1024.webp"
    }
  ],
  "/images/db06_hero.jpg": [
    {
      "width": 96,
      "src": "/images/responsive/db06_hero-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/db06_hero-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/db06_hero-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/db06_hero-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/db06_hero-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/db06_hero-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/db06_hero-1024.webp"
    }
  ],
  "/images/dbt10.jpg": [
    {
      "width": 96,
      "src": "/images/responsive/dbt10-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/dbt10-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/dbt10-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/dbt10-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/dbt10-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/dbt10-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/dbt10-1024.webp"
    },
    {
      "width": 1280,
      "src": "/images/responsive/dbt10-1280.webp"
    },
    {
      "width": 1920,
      "src": "/images/responsive/dbt10-1920.webp"
    }
  ],
  "/images/dpv01.jpg": [
    {
      "width": 96,
      "src": "/images/responsive/dpv01-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/dpv01-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/dpv01-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/dpv01-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/dpv01-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/dpv01-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/dpv01-1024.webp"
    },
    {
      "width": 1280,
      "src": "/images/responsive/dpv01-1280.webp"
    },
    {
      "width": 1920,
      "src": "/images/responsive/dpv01-1920.webp"
    }
  ],
  "/images/dss05.jpg": [
    {
      "width": 96,
      "src": "/images/responsive/dss05-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/dss05-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/dss05-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/dss05-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/dss05-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/dss05-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/dss05-1024.webp"
    },
    {
      "width": 1280,
      "src": "/images/responsive/dss05-1280.webp"
    },
    {
      "width": 1920,
      "src": "/images/responsive/dss05-1920.webp"
    }
  ],
  "/images/dtd01_main.jpg": [
    {
      "width": 96,
      "src": "/images/responsive/dtd01_main-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/dtd01_main-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/dtd01_main-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/dtd01_main-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/dtd01_main-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/dtd01_main-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/dtd01_main-1024.webp"
    }
  ],
  "/images/dtd02_main.jpg": [
    {
      "width": 96,
      "src": "/images/responsive/dtd02_main-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/dtd02_main-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/dtd02_main-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/dtd02_main-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/dtd02_main-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/dtd02_main-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/dtd02_main-1024.webp"
    }
  ],
  "/images/dtd03_main.jpg": [
    {
      "width": 96,
      "src": "/images/responsive/dtd03_main-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/dtd03_main-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/dtd03_main-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/dtd03_main-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/dtd03_main-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/dtd03_main-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/dtd03_main-1024.webp"
    }
  ],
  "/images/logo-ws.png": [
    {
      "width": 96,
      "src": "/images/responsive/logo-ws-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/logo-ws-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/logo-ws-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/logo-ws-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/logo-ws-640.webp"
    },
    {
      "width": 641,
      "src": "/images/responsive/logo-ws-641.webp"
    }
  ],
  "/images/logo_sp.png": [
    {
      "width": 96,
      "src": "/images/responsive/logo_sp-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/logo_sp-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/logo_sp-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/logo_sp-480.webp"
    },
    {
      "width": 595,
      "src": "/images/responsive/logo_sp-595.webp"
    }
  ],
  "/images/mv_5HY_bp_a.jpg": [
    {
      "width": 96,
      "src": "/images/responsive/mv_5HY_bp_a-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/mv_5HY_bp_a-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/mv_5HY_bp_a-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/mv_5HY_bp_a-480.webp"
    },
    {
      "width": 636,
      "src": "/images/responsive/mv_5HY_bp_a-636.webp"
    }
  ],
  "/images/o0tosa_2000x.webp": [
    {
      "width": 96,
      "src": "/images/responsive/o0tosa_2000x-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/o0tosa_2000x-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/o0tosa_2000x-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/o0tosa_2000x-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/o0tosa_2000x-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/o0tosa_2000x-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/o0tosa_2000x-1024.webp"
    },
    {
      "width": 1280,
      "src": "/images/responsive/o0tosa_2000x-1280.webp"
    }
  ],
  "/images/saekanofine_1024x1024.webp": [
    {
      "width": 96,
      "src": "/images/responsive/saekanofine_1024x1024-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/saekanofine_1024x1024-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/saekanofine_1024x1024-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/saekanofine_1024x1024-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/saekanofine_1024x1024-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/saekanofine_1024x1024-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/saekanofine_1024x1024-1024.webp"
    }
  ],
  "/images/topheader_782_440_dtb06_01.jpeg": [
    {
      "width": 96,
      "src": "/images/responsive/topheader_782_440_dtb06_01-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/topheader_782_440_dtb06_01-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/topheader_782_440_dtb06_01-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/topheader_782_440_dtb06_01-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/topheader_782_440_dtb06_01-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/topheader_782_440_dtb06_01-768.webp"
    },
    {
      "width": 782,
      "src": "/images/responsive/topheader_782_440_dtb06_01-782.webp"
    }
  ],
  "/images/vs05.png": [
    {
      "width": 96,
      "src": "/images/responsive/vs05-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/vs05-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/vs05-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/vs05-480.webp"
    },
    {
      "width": 605,
      "src": "/images/responsive/vs05-605.webp"
    }
  ],
  "/images/vs06.png": [
    {
      "width": 96,
      "src": "/images/responsive/vs06-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/vs06-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/vs06-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/vs06-480.webp"
    },
    {
      "width": 605,
      "src": "/images/responsive/vs06-605.webp"
    }
  ],
  "/images/ws-uma-td01.jpg": [
    {
      "width": 96,
      "src": "/images/responsive/ws-uma-td01-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/ws-uma-td01-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/ws-uma-td01-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/ws-uma-td01-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/ws-uma-td01-640.webp"
    },
    {
      "width": 707,
      "src": "/images/responsive/ws-uma-td01-707.webp"
    }
  ],
  "/images/ws-uma-td2.jpg": [
    {
      "width": 96,
      "src": "/images/responsive/ws-uma-td2-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/ws-uma-td2-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/ws-uma-td2-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/ws-uma-td2-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/ws-uma-td2-640.webp"
    },
    {
      "width": 707,
      "src": "/images/responsive/ws-uma-td2-707.webp"
    }
  ],
  "/images/wsbp-Lycoris.png": [
    {
      "width": 96,
      "src": "/images/responsive/wsbp-Lycoris-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/wsbp-Lycoris-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/wsbp-Lycoris-320.webp"
    },
    {
      "width": 328,
      "src": "/images/responsive/wsbp-Lycoris-328.webp"
    }
  ],
  "/images/wsbp-pd.jpg": [
    {
      "width": 96,
      "src": "/images/responsive/wsbp-pd-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/wsbp-pd-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/wsbp-pd-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/wsbp-pd-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/wsbp-pd-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/wsbp-pd-768.webp"
    },
    {
      "width": 1024,
      "src": "/images/responsive/wsbp-pd-1024.webp"
    },
    {
      "width": 1280,
      "src": "/images/responsive/wsbp-pd-1280.webp"
    },
    {
      "width": 1400,
      "src": "/images/responsive/wsbp-pd-1400.webp"
    }
  ],
  "/images/wstd-PD.jpg": [
    {
      "width": 96,
      "src": "/images/responsive/wstd-PD-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/wstd-PD-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/wstd-PD-320.webp"
    },
    {
      "width": 480,
      "src": "/images/responsive/wstd-PD-480.webp"
    },
    {
      "width": 640,
      "src": "/images/responsive/wstd-PD-640.webp"
    },
    {
      "width": 768,
      "src": "/images/responsive/wstd-PD-768.webp"
    },
    {
      "width": 779,
      "src": "/images/responsive/wstd-PD-779.webp"
    }
  ],
  "/images/wstd-lycoris.png": [
    {
      "width": 96,
      "src": "/images/responsive/wstd-lycoris-96.webp"
    },
    {
      "width": 160,
      "src": "/images/responsive/wstd-lycoris-160.webp"
    },
    {
      "width": 320,
      "src": "/images/responsive/wstd-lycoris-320.webp"
    },
    {
      "width": 323,
      "src": "/images/responsive/wstd-lycoris-323.webp"
    }
  ]
};

export function imageSrcSet(src: string): string | undefined {
  const variants = responsiveImages[src];
  if (!variants?.length) return undefined;
  return variants.map((item) => `${item.src} ${item.width}w`).join(', ');
}

export function imageSizes(src: string): string | undefined {
  if (!responsiveImages[src]?.length) return undefined;
  if (src.includes('cropped-Logo-EG')) return '66px';
  if (src.includes('PhoneIcon') || src.includes('LocationIcon') || src.includes('EmailIcon')) return '24px';
  if (src.includes('Poster') || src.includes('CARDFIGHT-VG-JAPAN')) return '(max-width: 768px) 100vw, 842px';
  return '(max-width: 640px) 100vw, (max-width: 1200px) 50vw, 640px';
}
