import json
import pathlib
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "public" / "images"
OUT_DIR = SRC_DIR / "responsive"
OUT_DIR.mkdir(parents=True, exist_ok=True)

WIDTHS = [96, 160, 320, 480, 640, 768, 1024, 1280]
QUALITY = 82

responsive = {}

for src in sorted(SRC_DIR.iterdir()):
    if not src.is_file() or src.name == ".gitkeep":
        continue
    if src.suffix.lower() == ".svg":
        continue
    try:
        im = Image.open(src)
        im.load()
    except Exception as exc:
        print(f"skip {src.name}: {exc}")
        continue

    w, h = im.size
    entries = []
    # For tiny icons/logos include small choices; for content images include normal responsive widths.
    candidate_widths = [x for x in WIDTHS if x <= w]
    if w not in candidate_widths:
        candidate_widths.append(w)
    candidate_widths = sorted(set(candidate_widths))

    for target_w in candidate_widths:
        if target_w < 64:
            continue
        target_h = max(1, round(h * (target_w / w)))
        out_name = f"{src.stem}-{target_w}.webp"
        out = OUT_DIR / out_name
        if not out.exists():
            img = im.copy()
            if img.mode not in ("RGB", "RGBA"):
                img = img.convert("RGBA" if "A" in img.getbands() else "RGB")
            if target_w != w:
                img = img.resize((target_w, target_h), Image.Resampling.LANCZOS)
            img.save(out, "WEBP", quality=QUALITY, method=3)
        entries.append({"width": target_w, "src": f"/images/responsive/{out_name}"})

    responsive[f"/images/{src.name}"] = entries
    print(f"{src.name}: {w}x{h} -> {len(entries)} variants")

# Write TypeScript helper.
ts = """// Auto-generated by scripts/generate_responsive_images.py
// Provides static responsive srcSet values for Azure Static Website export.

export const responsiveImages: Record<string, { width: number; src: string }[]> = """ + json.dumps(responsive, indent=2) + """;

export function imageSrcSet(src: string): string | undefined {
  const variants = responsiveImages[src];
  if (!variants?.length) return undefined;
  return variants.map((item) => `${item.src} ${item.width}w`).join(', ');
}

export function imageSizes(src: string): string | undefined {
  if (!responsiveImages[src]?.length) return undefined;
  if (src.includes('cropped-Logo-EG')) return '66px';
  if (src.includes('PhoneIcon') || src.includes('LocationIcon') || src.includes('EmailIcon')) return '24px';
  if (src.includes('Poster') || src.includes('CARDFIGHT-VG-JAPAN')) return '(max-width: 768px) 100vw, 842px';
  return '(max-width: 640px) 100vw, (max-width: 1200px) 50vw, 640px';
}
"""
(ROOT / "src" / "lib" / "responsive-images.ts").write_text(ts, encoding="utf-8")
print(f"Wrote {ROOT / 'src/lib/responsive-images.ts'}")
print(f"Generated {sum(len(v) for v in responsive.values())} responsive variants")
